name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Build OpenSSL
        run: ./scripts/build_openssl.sh release
      - name: Build LLVM
        run: ./scripts/build_llvm.sh release
      - name: Build Gandiva
        run: ./scripts/build_gandiva.sh release
      - name: npm install
        run: npm install
      - name: npm run build:release
        run: npm run build:release
      - name: npm run test:node
        run: npm run test:node
      - name: npm run benchmark:browser
        run: npm run benchmark:browser
