name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build OpenSSL
      run: ./scripts/build_openssl.sh
    - name: Build LLVM
      run: ./scripts/build_llvm.sh
    - name: Build Gandiva
      run: ./scripts/build_gandiva.sh
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test
